name: "deploy"

on:
    push:
        branches: ["master"]

jobs:
    deploy-actions-example:
        runs-on: ubuntu-latest
        steps:
            uses: actions/checkout@v4
            run: echo "Hacemos Pull"
            run: echo "Correr migraciones"
            run: echo "Generar binario"
            run: echo "Otra cosa"
