name: "deploy"

on:
    push:
        branches: ["master"]

jobs:
    deploy-actions_example: #nombre del job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: python --version
